### PR TITLE
Slug update

### PR DESCRIPTION
**Pull request by dodget**
This PR resolves ATGU-2004 by:
- When the book slug is changed, find all content locations for the book where the old book
- Then replace the slug in the string with the new slug
- Then find all versions by the content's content_id, and replace the url with the new url

### CODE REVIEW

**Review by arthurian — COMMENTED** [review]
@dodget This looks pretty clean as it ensures that the old slug is updated to the new slug in the background, thumbnail, or banner content fields, or the version url field. I like that it only updates the necessary rows.

A few things I noticed while looking at this:

1) The `scalar_db_versions.content` field should be updated in addition to the existing fields. It's possible that media URLs may be embedded in the content, and we would want those URLs to get the slug update as well. 

2) The search and replace on `/oldslug/` => `/newslug/` as opposed to `http://localhost:8080/oldslug/` => `http://localhost:8080/newslug/` could result in false positives when updating content (less likely for URL fields). It looks like the previous code used the base URL to guard against that possibility. This worked because media URLs would either be absolute URLs including the slug, which would be updated accordingly, or URLs relative to the book (e.g. just `media/foo.jpg`), and would not be updated since they would work as expected after the slug change anyway.

    The problem for us is that our media URLs don't share the same base URL as the scalar system, which was the original assumption when using filesystem storage. 

3) The previous implementation consolidated the update into 1 SELECT and 3 UPDATE queries (4 total). So regardless of how many media files were associated with a book, a slug change operation only cost 4 queries. I think the changes here will incur a cost proportional to the number of media files.

I'm wondering if we could address some of these issues by reusing part of the original approach and substituting the correct base URL for media, rather than relying on the `base_url()`.  For scalar systems that use the default file storage, the configured media URL would be the same as the site base URL, so the behavior would be unchanged, and for systems that use S3 storage, it would point to the appropriate S3 URL: `https://<bucket>.s3.amazonaws.com/`. I imagine this could just be a new config value for setting the media url globally, which could be passed to the storage adapter as well, to override the default URL that's produced.

What do you think?

**Comment by dodget** [comment]
Thanks for the thorough review. I hadn't considered that the urls could be embedded in versions.content blobs. Thats a bit trickier.

I guess we could just define a new config, something like `media_url()`. Seems simple enough. If that doesn't work for whatever reason, then figuring out the appropriate url should be trivial. I'll give that a run.

**Comment by dodget** [comment]
@arthurian - I've made updates based on your suggestions, and its redeployed to dev. Let me know what you think!

**Comment by arthurian** [comment]
@dodget This looks great! Very simple and should have good performance for larger books. I just pushed one additional commit after doing some testing on the dev server. I think this should handle all of the edge cases, but if you could take a look at the changes and confirm yourself that would be great. If it looks good to you, then I'm comfortable merging this.

**Pull request merged**
